language: php

before_script:
  - composer update --dev

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script:
 - php vendor/bin/phpunit --configuration phpunit.xml.travisci --coverage-text --coverage-clover ./build/logs/clover.xml